### ISSUE TITLE
"i" triggers sound+confetti when typing

### ISSUE THREAD

**Issue by SoopCanSam** [QuadMesh/QMLC_YippeeKeyMod#1]
When typing in chat and also when typing on the "sign" "emote", in the MoreEmotes mod, the Yippee sound triggers still and so does the confetti if enabled. 

We do have the "NiceChat" mod installed but I doubt that is the issue.

More_Emotes ThunderStore: https://thunderstore.io/c/lethal-company/p/Sligili/More_Emotes/

Thank you for a fun mod :)

**Comment by ThisMight** [comment]
That does sound annoying, I don't know if there is a way to check if these mod's menus are open. Chat sounds doable. We'll check it out asap!

**Comment by ThisMight** [comment]
Testing for chatting itself is done, I will now check to see if I can patch it when using the mods you provided.

**Comment by ThisMight** [comment]
More-emotes works with this patch, I will close this issue as soon as I've pushed the update to github & Thunderstore.
