### ISSUE TITLE
Csync update breaks something in Yippee :(

### ISSUE THREAD

**Issue by Roobotics** [QuadMesh/QMLC_YippeeKeyMod#2]
Your dependancy CSync just released 2.0.0 and once you are on the ship, with only this mod enabled and CSync updated to 2.0.0, you can't leave via the exit menu anymore! Requires ALT+F4 to terminate. Facility Meltdown also uses Csync and having that enabled on CSync 2.0.0 version, doesn't cause this issue.

My friends love this silly mod, I'll try to keep everyone on CSync 1.0.8 for now, but folks like to update to the latest usually, so fyi there is a new incompatibility.

**Comment by Test-Account666** [comment]
For now, use this version:
https://thunderstore.io/c/lethal-company/p/TestAccount666/FixedYippeeKeyMod/

But switch back to the original as soon as it updates :)

**Comment by ThisMight** [comment]
Sorry for the delayed response, I will be investigating the issue as soon as I can. Though this is not the only bug found in the past days.

**Comment by ThisMight** [comment]
> For now, use this version: https://thunderstore.io/c/lethal-company/p/TestAccount666/FixedYippeeKeyMod/
> 
> But switch back to the original as soon as it updates :)

I'd also recommend people like this to PR instead of reposting mods, More 'Ethically pleasing' to the open source community lol

**Comment by Roobotics** [comment]
Thanks for patching this to work with latest. Now my group can get back to the yippee'ing

Also 2 different folks have reported they couldn't yippee (on the old version, with correct CSync) that'd been stable.. I'll see if that issue persists or has any discernible root cause and report back if so. I had them check their bindings and everything, but they couldn't make it function. We had ~6 or 7 players via MoreCompany, others could yippee without issues, and were also seen and heard by those that couldn't yippee, I believe. I doubt the root cause is identifiable from these basic details alone, but some datapoints.

**Comment by ThisMight** [comment]
> Thanks for patching this to work with latest. Now my group can get back to the yippee'ing
> 
> Also 2 different folks have reported they couldn't yippee (on the old version, with correct CSync) that'd been stable.. I'll see if that issue persists or has any discernible root cause and report back if so. I had them check their bindings and everything, but they couldn't make it function. We had ~6 or 7 players via MoreCompany, others could yippee without issues, and were also seen and heard by those that couldn't yippee, I believe. I doubt the root cause is identifiable from these basic details alone, but some datapoints.

The best you can do in this situation is telling your friends to enable logging. The players that lose the ability to Yippee will have the reasoning and events leading up to the issue in their logs. If you happen to come across this issue on 1.3.2 or later, you're welcome to create a new Issue regarding the issue. (And if you have them, the logs)

**Comment by Roobotics** [comment]
FYI, you are likely already aware, but the creator of CSync has jumped ship and it's already marked as a depreciated dependancy. 

I'd like to point out that your mod has a rather static function, so needing a config-sync dependency seems a bit much, the only feature that might warrant it is if the host is going to toggle the 'affects mobs' flag while alive/dead after the game starts. But otherwise, using thunderstore or R2modman, all relevant CFG files get exported as file, or copied over via cloud when using the create-code export function.

There is also a new branch of CSync someone opened up to fill the niche, if that's easier: https://thunderstore.io/c/lethal-company/p/Sigurd/CSync/
